package exploration

import (
	"backend/agentools"
	"context"
	"strings"
	"testing"
	"time"

	"github.com/cloudwego/eino/adk"
	"github.com/cloudwego/eino/schema"
)

type scriptedResumableAgent struct {
	runFn   func(ctx context.Context, input *adk.AgentInput) *adk.AsyncIterator[*adk.AgentEvent]
	called  bool
	inputs  []*adk.AgentInput
	resumed bool
}

func (f *scriptedResumableAgent) Name(_ context.Context) string {
	return "scripted-deep-agent"
}

func (f *scriptedResumableAgent) Description(_ context.Context) string {
	return "scripted deep agent"
}

func (f *scriptedResumableAgent) Run(ctx context.Context, input *adk.AgentInput, _ ...adk.AgentRunOption) *adk.AsyncIterator[*adk.AgentEvent] {
	f.called = true
	f.inputs = append(f.inputs, input)
	if f.runFn != nil {
		return f.runFn(ctx, input)
	}
	iter, gen := adk.NewAsyncIteratorPair[*adk.AgentEvent]()
	go func() {
		defer gen.Close()
		gen.Send(adk.EventFromMessage(schema.AssistantMessage("SUMMARY: no graph changes were needed this run", nil), nil, schema.Assistant, ""))
	}()
	return iter
}

func (f *scriptedResumableAgent) Resume(_ context.Context, _ *adk.ResumeInfo, _ ...adk.AgentRunOption) *adk.AsyncIterator[*adk.AgentEvent] {
	f.resumed = true
	iter, gen := adk.NewAsyncIteratorPair[*adk.AgentEvent]()
	gen.Close()
	return iter
}

func TestRunMainAgentGraphBatchUsesDeepAgentSummary(t *testing.T) {
	domain := newScriptedExplorationDomain()
	agent := &scriptedResumableAgent{}
	domain.DeepAgent = agent

	session := &ExplorationSession{
		ID:                  "ws-deep-summary",
		Topic:               "agent graph",
		OutputGoal:          "grow graph",
		ActiveOpportunityID: "node-root",
		Nodes:               []Node{{ID: "node-root", Type: NodeOpportunity, Title: "Root"}},
	}
	state := &RuntimeWorkspaceState{
		Balance: BalanceState{Divergence: 0.4, Research: 0.5, Aggression: 0.6},
	}

	summary, err := domain.runMainAgentGraphBatch(context.Background(), session.ID, session, state)
	if err != nil {
		t.Fatalf("runMainAgentGraphBatch failed: %v", err)
	}
	if !agent.called {
		t.Fatal("expected DeepAgent to be called")
	}
	if summary != "expanded the active branch through append_graph_batch" {
		t.Fatalf("unexpected summary: %q", summary)
	}
	if len(agent.inputs) != 1 || len(agent.inputs[0].Messages) != 1 {
		t.Fatalf("expected a single user message, got %+v", agent.inputs)
	}
	prompt := agent.inputs[0].Messages[0].Content
	if !strings.Contains(prompt, "SUMMARY:") {
		t.Fatalf("expected prompt to require fixed summary output, got %q", prompt)
	}
	if !strings.Contains(prompt, session.ActiveOpportunityID) {
		t.Fatalf("expected prompt to include active opportunity id, got %q", prompt)
	}
}

func TestRunSingleAgentPassUsesDeepAgentToGrowGraph(t *testing.T) {
	domain := newScriptedExplorationDomain()
	snapshot, err := domain.CreateWorkspace(CreateWorkspaceReq{Topic: "agent graph", OutputGoal: "runtime"})
	if err != nil {
		t.Fatalf("create workspace: %v", err)
	}

	activeID := snapshot.Exploration.ActiveOpportunityID
	domain.DeepAgent = &scriptedResumableAgent{
		runFn: func(ctx context.Context, input *adk.AgentInput) *adk.AsyncIterator[*adk.AgentEvent] {
			iter, gen := adk.NewAsyncIteratorPair[*adk.AgentEvent]()
			go func() {
				defer gen.Close()
				_, err := domain.AppendGraphBatch(ctx, agentools.AppendGraphBatchParams{
					WorkspaceID: snapshot.Exploration.ID,
					Nodes: []agentools.AppendGraphBatchNode{{
						ID:      "idea-deep-runtime",
						Type:    string(NodeIdea),
						Title:   "Deep runtime idea",
						Summary: "Generated by the deep exploration agent",
						Status:  string(NodeActive),
						Depth:   5,
					}},
					Edges: []agentools.AppendGraphBatchEdge{{
						ID:   "edge-deep-runtime",
						From: activeID,
						To:   "idea-deep-runtime",
						Type: string(EdgeLeadsTo),
					}},
				})
				if err != nil {
					gen.Send(&adk.AgentEvent{Err: err})
					return
				}
				gen.Send(adk.EventFromMessage(schema.AssistantMessage("SUMMARY: append_graph_batch added 1 nodes and 1 edges", nil), nil, schema.Assistant, ""))
			}()
			return iter
		},
	}

	runID, launched := domain.triggerRun(context.Background(), snapshot.Exploration.ID, string(RunSourceManual))
	if !launched {
		t.Fatal("expected manual trigger to launch")
	}
	if runID == "" {
		t.Fatal("expected run id")
	}

	time.Sleep(150 * time.Millisecond)

	updated, ok := domain.GetWorkspace(snapshot.Exploration.ID)
	if !ok {
		t.Fatal("expected workspace after run")
	}
	if !hasNode(updated.DirectionMap.Nodes, "idea-deep-runtime") {
		t.Fatal("expected deep agent run to append graph node through tool")
	}

	state, ok := domain.GetRuntimeState(snapshot.Exploration.ID)
	if !ok {
		t.Fatal("expected runtime state")
	}
	if len(state.Results) == 0 {
		t.Fatal("expected runtime results")
	}
	lastResult := state.Results[len(state.Results)-1]
	if lastResult.Summary != "append_graph_batch added 1 nodes and 1 edges" {
		t.Fatalf("expected fixed-format summary, got %q", lastResult.Summary)
	}
}
